version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      vite:
        patterns:
          - "vite*"
          - "@vitejs/*"
      typescript:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
